export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';

