export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const LIKE_SHOES = 'LIKE_SHOES';
export const DISLIKE_SHOES = 'DISLIKE_SHOES';
